name: utopia_hotreload
description: Advanced hot reload and hot restart functionality for Dart applications with true VM-based hot reload capabilities, similar to Flutter's development experience.
version: 1.0.0

homepage: https://github.com/utopia-dart/utopia_hotreload
repository: https://github.com/utopia-dart/utopia_hotreload
issue_tracker: https://github.com/utopia-dart/utopia_hotreload/issues
documentation: https://github.com/utopia-dart/utopia_hotreload#readme

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  vm_service: ^15.0.0
  watcher: ^1.1.0
  path: ^1.8.0
  meta: ^1.9.0

dev_dependencies:
  test: ^1.21.0
  http: ^1.1.0
  lints: ^6.0.0

topics:
  - hot-reload
  - development
  - server
  - dart-vm
  - file-watching
